import '../models/attendance_stats.dart';
import '../models/student_attendance_record.dart';
import '../models/student_course.dart';
import '../models/student_profile.dart';

/// مخزن البيانات النموذجية المستقل والمفصل لدور الطالب
class MockStudentData {
  /// الملف الشخصي الافتراضي للطالب
  static const StudentProfile defaultProfile = StudentProfile(
    id: 'usr-std-001',
    studentNumber: 'STD-2023-4019',
    fullName: 'أحمد علي عبد الله',
    email: 'ahmed.ali@univ.edu',
    phone: '+967 771 234 567',
    departmentId: 'dep-it-01',
    departmentName: 'هندسة تقنية المعلومات',
    collegeName: 'كلية الهندسة والحاسوب',
    academicYearId: 'ay-2025-2026',
    academicYearName: '2025/2026',
    academicLevel: 3,
    accountState: StudentAccountState.active,
    deviceState: StudentDeviceState.bound,
    boundDeviceId: 'dev-sec-samsung-n960u',
  );

  /// قائمة المقررات والشعب المسجلة للطالب في الفصل الحالي
  static const List<StudentCourse> defaultCourses = [
    StudentCourse(
      id: 'crs-001',
      courseCode: 'CS301',
      courseName: 'هندسة البرمجيات المتقدمة',
      creditHours: 3,
      sectionId: 'sec-001-p',
      sectionNumber: 'شعبة 1',
      sectionType: SectionType.practical,
      teacherName: 'د. محمد السعيد',
      totalLectures: 14,
      attendedLectures: 13,
      absentLectures: 1,
      lateLectures: 0,
      excusedLectures: 0,
      roomName: 'معمل الحاسوب 3',
      scheduleTime: 'الأحد 08:00 ص - 10:00 ص',
    ),
    StudentCourse(
      id: 'crs-002',
      courseCode: 'CS302',
      courseName: 'نظم إدارة قواعد البيانات',
      creditHours: 3,
      sectionId: 'sec-002-t',
      sectionNumber: 'شعبة 2',
      sectionType: SectionType.theoretical,
      teacherName: 'أ.د. عبد الرحمن النور',
      totalLectures: 14,
      attendedLectures: 12,
      absentLectures: 2,
      lateLectures: 1,
      excusedLectures: 0,
      roomName: 'قاعة المحاضرات الكبرى 1',
      scheduleTime: 'الإثنين 10:00 ص - 12:00 م',
    ),
    StudentCourse(
      id: 'crs-003',
      courseCode: 'IT305',
      courseName: 'أمن الشبكات والمعلومات',
      creditHours: 3,
      sectionId: 'sec-003-p',
      sectionNumber: 'شعبة 1',
      sectionType: SectionType.practical,
      teacherName: 'م. سارة القدسي',
      totalLectures: 12,
      attendedLectures: 9,
      absentLectures: 3,
      lateLectures: 1,
      excusedLectures: 0,
      roomName: 'معمل الشبكات 2',
      scheduleTime: 'الثلاثاء 12:00 م - 02:00 م',
    ),
    StudentCourse(
      id: 'crs-004',
      courseCode: 'IT308',
      courseName: 'تطوير تطبيقات الهواتف الذكية',
      creditHours: 3,
      sectionId: 'sec-004-p',
      sectionNumber: 'شعبة 1',
      sectionType: SectionType.practical,
      teacherName: 'م. أواب النزيلي',
      totalLectures: 14,
      attendedLectures: 14,
      absentLectures: 0,
      lateLectures: 0,
      excusedLectures: 0,
      roomName: 'معمل البرمجيات 4',
      scheduleTime: 'الأربعاء 08:00 ص - 10:00 ص',
    ),
  ];

  /// سجلات الحضور السابقة التاريخية
  static final List<StudentAttendanceRecord> defaultAttendanceHistory = [
    StudentAttendanceRecord(
      id: 'rec-001',
      sessionId: 'ses-101',
      courseId: 'crs-004',
      courseCode: 'IT308',
      courseName: 'تطوير تطبيقات الهواتف الذكية',
      sectionNumber: 'شعبة 1',
      teacherName: 'م. أواب النزيلي',
      sessionDate: DateTime.now().subtract(const Duration(hours: 3)),
      attendanceState: 'PRESENT',
      verificationMethod: 'QR',
      verifiedAt: DateTime.now().subtract(const Duration(hours: 2, minutes: 55)),
    ),
    StudentAttendanceRecord(
      id: 'rec-002',
      sessionId: 'ses-100',
      courseId: 'crs-001',
      courseCode: 'CS301',
      courseName: 'هندسة البرمجيات المتقدمة',
      sectionNumber: 'شعبة 1',
      teacherName: 'د. محمد السعيد',
      sessionDate: DateTime.now().subtract(const Duration(days: 1)),
      attendanceState: 'PRESENT',
      verificationMethod: 'BIOMETRIC',
      verifiedAt: DateTime.now().subtract(const Duration(days: 1)).add(const Duration(minutes: 4)),
    ),
    StudentAttendanceRecord(
      id: 'rec-003',
      sessionId: 'ses-099',
      courseId: 'crs-003',
      courseCode: 'IT305',
      courseName: 'أمن الشبكات والمعلومات',
      sectionNumber: 'شعبة 1',
      teacherName: 'م. سارة القدسي',
      sessionDate: DateTime.now().subtract(const Duration(days: 2)),
      attendanceState: 'LATE',
      verificationMethod: 'QR',
      verifiedAt: DateTime.now().subtract(const Duration(days: 2)).add(const Duration(minutes: 18)),
    ),
    StudentAttendanceRecord(
      id: 'rec-004',
      sessionId: 'ses-098',
      courseId: 'crs-002',
      courseCode: 'CS302',
      courseName: 'نظم إدارة قواعد البيانات',
      sectionNumber: 'شعبة 2',
      teacherName: 'أ.د. عبد الرحمن النور',
      sessionDate: DateTime.now().subtract(const Duration(days: 4)),
      attendanceState: 'ABSENT',
      verificationMethod: 'MANUAL',
      note: 'عدم الحضور للجلسة النظرية',
    ),
    StudentAttendanceRecord(
      id: 'rec-005',
      sessionId: 'ses-097',
      courseId: 'crs-001',
      courseCode: 'CS301',
      courseName: 'هندسة البرمجيات المتقدمة',
      sectionNumber: 'شعبة 1',
      teacherName: 'د. محمد السعيد',
      sessionDate: DateTime.now().subtract(const Duration(days: 7)),
      attendanceState: 'PRESENT',
      verificationMethod: 'QR',
    ),
  ];

  /// الإحصائيات التراكمية
  static const AttendanceStats defaultStats = AttendanceStats(
    totalSessions: 54,
    totalPresent: 48,
    totalAbsent: 4,
    totalLate: 2,
    totalExcused: 0,
    totalCourses: 4,
  );
}
