import '../models/delegate_section.dart';
import '../models/delegate_session.dart';
import '../models/delegate_student_entry.dart';

/// بيانات نموذجية واقعية لاختبار وتطوير واجهات المندوب دون الحاجة للاتصال بالإنترنت
class MockDelegateData {
  MockDelegateData._();

  /// الشعب الأكاديمية المفوض بها هذا المندوب
  static final List<DelegateSection> sections = [
    const DelegateSection(
      id: 'sec-001-p',
      courseId: 'crs-001',
      courseCode: 'CS301',
      courseName: 'هندسة البرمجيات المتقدمة',
      sectionNumber: '01',
      sectionType: DelegateSectionType.practical,
      teacherId: 'tch-001',
      teacherName: 'د. محمد السعيد',
      totalStudents: 28,
      roomName: 'معمل الحاسوب 3',
      scheduleTime: 'الأحد 08:00 ص - 10:00 ص',
      isActive: true,
    ),
    const DelegateSection(
      id: 'sec-004-p',
      courseId: 'crs-004',
      courseCode: 'IT308',
      courseName: 'تطوير تطبيقات الهواتف الذكية',
      sectionNumber: '02',
      sectionType: DelegateSectionType.practical,
      teacherId: 'tch-004',
      teacherName: 'م. أواب النزيلي',
      totalStudents: 32,
      roomName: 'معمل البرمجيات 1',
      scheduleTime: 'الثلاثاء 10:00 ص - 12:00 م',
      isActive: true,
    ),
    const DelegateSection(
      id: 'sec-002-t',
      courseId: 'crs-002',
      courseCode: 'CS302',
      courseName: 'نظم إدارة قواعد البيانات',
      sectionNumber: '01',
      sectionType: DelegateSectionType.theoretical,
      teacherId: 'tch-002',
      teacherName: 'د. خالد عبد الرحمن',
      totalStudents: 45,
      roomName: 'مدرج ابن الهيثم (B)',
      scheduleTime: 'الخميس 08:00 ص - 10:00 ص',
      isActive: true,
    ),
  ];

  /// الجلسات السابقة والحديثة
  static final List<DelegateSession> recentSessions = [
    DelegateSession(
      id: 'ses-del-101',
      sectionId: 'sec-004-p',
      courseCode: 'IT308',
      courseName: 'تطوير تطبيقات الهواتف الذكية',
      sectionNumber: '02',
      sectionType: DelegateSectionType.practical,
      teacherName: 'م. أواب النزيلي',
      delegateId: 'usr-std-001',
      delegateName: 'أحمد علي عبد الله',
      sessionState: DelegateSessionState.synced,
      openedAt: DateTime.now().subtract(const Duration(days: 2, hours: 4)),
      closedAt: DateTime.now().subtract(const Duration(days: 2, hours: 2)),
      syncedAt: DateTime.now().subtract(const Duration(days: 2, hours: 1)),
      totalExpectedStudents: 32,
      attendedCount: 30,
      roomName: 'معمل البرمجيات 1',
      isOfflineMode: true,
      syncRecordId: 'sync-rec-8091',
    ),
    DelegateSession(
      id: 'ses-del-102',
      sectionId: 'sec-001-p',
      courseCode: 'CS301',
      courseName: 'هندسة البرمجيات المتقدمة',
      sectionNumber: '01',
      sectionType: DelegateSectionType.practical,
      teacherName: 'د. محمد السعيد',
      delegateId: 'usr-std-001',
      delegateName: 'أحمد علي عبد الله',
      sessionState: DelegateSessionState.closed,
      openedAt: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
      closedAt: DateTime.now().subtract(const Duration(days: 1, hours: 1)),
      totalExpectedStudents: 28,
      attendedCount: 26,
      roomName: 'معمل الحاسوب 3',
      isOfflineMode: true,
    ),
  ];

  /// كشف الطلاب للشعبة (CS301 / IT308)
  static List<DelegateStudentEntry> getStudentsRoster(String sectionId) {
    return [
      DelegateStudentEntry(
        studentId: 'std-001',
        studentNumber: 'STD-2023-4019',
        fullName: 'أحمد علي عبد الله',
        departmentName: 'هندسة تقنية المعلومات',
        attendanceState: 'PRESENT',
        attendanceMethod: 'QR',
        markedAt: DateTime.now().subtract(const Duration(minutes: 15)),
        isVerified: true,
      ),
      DelegateStudentEntry(
        studentId: 'std-002',
        studentNumber: 'STD-2023-4020',
        fullName: 'سارة محمد القحطاني',
        departmentName: 'هندسة تقنية المعلومات',
        attendanceState: 'PRESENT',
        attendanceMethod: 'QR',
        markedAt: DateTime.now().subtract(const Duration(minutes: 14)),
        isVerified: true,
      ),
      DelegateStudentEntry(
        studentId: 'std-003',
        studentNumber: 'STD-2023-4021',
        fullName: 'عبد الرحمن خالد العمري',
        departmentName: 'علوم الحاسوب',
        attendanceState: 'PRESENT',
        attendanceMethod: 'BIOMETRIC',
        markedAt: DateTime.now().subtract(const Duration(minutes: 12)),
        isVerified: true,
      ),
      DelegateStudentEntry(
        studentId: 'std-004',
        studentNumber: 'STD-2023-4022',
        fullName: 'فاطمة صالح النجار',
        departmentName: 'هندسة تقنية المعلومات',
        attendanceState: 'LATE',
        attendanceMethod: 'QR',
        markedAt: DateTime.now().subtract(const Duration(minutes: 5)),
        isVerified: true,
      ),
      const DelegateStudentEntry(
        studentId: 'std-005',
        studentNumber: 'STD-2023-4023',
        fullName: 'عمر ياسين باجعفر',
        departmentName: 'نظم المعلومات',
        attendanceState: 'ABSENT',
        isVerified: false,
      ),
      DelegateStudentEntry(
        studentId: 'std-006',
        studentNumber: 'STD-2023-4024',
        fullName: 'ريم عبد العزيز المهندس',
        departmentName: 'هندسة تقنية المعلومات',
        attendanceState: 'PRESENT',
        attendanceMethod: 'QR',
        markedAt: DateTime.now().subtract(const Duration(minutes: 10)),
        isVerified: true,
      ),
      DelegateStudentEntry(
        studentId: 'std-007',
        studentNumber: 'STD-2023-4025',
        fullName: 'حسام ناصر الشمري',
        departmentName: 'علوم الحاسوب',
        attendanceState: 'EXCUSED',
        attendanceMethod: 'MANUAL',
        markedAt: DateTime.now().subtract(const Duration(minutes: 20)),
        manualReason: 'عذر طبي معتمد من الكلية',
        isVerified: true,
      ),
      DelegateStudentEntry(
        studentId: 'std-008',
        studentNumber: 'STD-2023-4026',
        fullName: 'نورة إبراهيم السبيعي',
        departmentName: 'هندسة تقنية المعلومات',
        attendanceState: 'PRESENT',
        attendanceMethod: 'QR',
        markedAt: DateTime.now().subtract(const Duration(minutes: 8)),
        isVerified: true,
      ),
      const DelegateStudentEntry(
        studentId: 'std-009',
        studentNumber: 'STD-2023-4027',
        fullName: 'طارق زياد العتيبي',
        departmentName: 'هندسة تقنية المعلومات',
        attendanceState: 'ABSENT',
        isVerified: false,
      ),
      DelegateStudentEntry(
        studentId: 'std-010',
        studentNumber: 'STD-2023-4028',
        fullName: 'مها فيصل الحربي',
        departmentName: 'نظم المعلومات',
        attendanceState: 'PRESENT',
        attendanceMethod: 'QR',
        markedAt: DateTime.now().subtract(const Duration(minutes: 3)),
        isVerified: true,
      ),
      DelegateStudentEntry(
        studentId: 'std-011',
        studentNumber: 'STD-2023-4029',
        fullName: 'يوسف جمال اليافعي',
        departmentName: 'علوم الحاسوب',
        attendanceState: 'PRESENT',
        attendanceMethod: 'QR',
        markedAt: DateTime.now().subtract(const Duration(minutes: 2)),
        isVerified: true,
      ),
      const DelegateStudentEntry(
        studentId: 'std-012',
        studentNumber: 'STD-2023-4030',
        fullName: 'بلقيس عبد الله الأحمدي',
        departmentName: 'هندسة تقنية المعلومات',
        attendanceState: 'ABSENT',
        isVerified: false,
      ),
    ];
  }
}
