import '../models/lab_group.dart';
import '../models/lab_session.dart';
import '../models/lab_student_record.dart';

/// بيانات تجريبية واقعية لأستاذ المعمل العملي (Mock Practical Data)
class MockPracticalData {
  static const Map<String, dynamic> teacherProfile = {
    'id': 'usr-prac-001',
    'full_name': 'م. عمر عبد الرحمن العريقي',
    'teacher_title': 'أستاذ عملي / معيد معتمد',
    'department_name': 'قسم تكنولوجيا المعلومات وهندسة البرمجيات',
    'email': 'omar.alariqi@university.edu.ye',
    'active_labs_count': 4,
    'total_students_supervised': 118,
    'pending_exceptions_count': 3,
  };

  static final List<LabGroup> labGroups = [
    const LabGroup(
      id: 'grp-001',
      courseId: 'crs-swe-301',
      courseCode: 'CS301',
      courseName: 'هندسة البرمجيات المتقدمة',
      sectionNumber: '01',
      groupName: 'مجموعة A - معمل البرمجيات 1',
      groupType: LabGroupType.softwareLab,
      roomName: 'معمل الحاسوب 3',
      scheduleTime: 'الأحد 08:00 ص - 10:00 ص',
      totalStudents: 30,
      attendedStudents: 26,
      delegateId: 'usr-std-001',
      delegateName: 'أحمد علي عبد الله',
      isLiveNow: true,
      activeSessionId: 'ses-prac-live-01',
    ),
    const LabGroup(
      id: 'grp-002',
      courseId: 'crs-swe-301',
      courseCode: 'CS301',
      courseName: 'هندسة البرمجيات المتقدمة',
      sectionNumber: '02',
      groupName: 'مجموعة B - معمل البرمجيات 1',
      groupType: LabGroupType.softwareLab,
      roomName: 'معمل الحاسوب 3',
      scheduleTime: 'الأحد 10:00 ص - 12:00 م',
      totalStudents: 28,
      attendedStudents: 24,
      delegateId: 'usr-std-004',
      delegateName: 'خالد عمر باوزير',
      isLiveNow: false,
    ),
    const LabGroup(
      id: 'grp-003',
      courseId: 'crs-net-302',
      courseCode: 'IT302',
      courseName: 'شبكات الحاسوب المتقدمة',
      sectionNumber: '01',
      groupName: 'مجموعة A - معمل سيسكو والشبكات',
      groupType: LabGroupType.networkLab,
      roomName: 'معمل الشبكات التخصصي',
      scheduleTime: 'الثلاثاء 08:00 ص - 10:00 ص',
      totalStudents: 32,
      attendedStudents: 29,
      delegateId: 'usr-std-007',
      delegateName: 'ياسر فاروق الصبري',
      isLiveNow: false,
    ),
    const LabGroup(
      id: 'grp-004',
      courseId: 'crs-db-303',
      courseCode: 'CS303',
      courseName: 'إدارة قواعد البيانات ونظم SQL',
      sectionNumber: '01',
      groupName: 'مجموعة A - معمل الخوادم والبيانات',
      groupType: LabGroupType.databaseLab,
      roomName: 'معمل الحاسوب 2',
      scheduleTime: 'الأربعاء 10:00 ص - 12:00 م',
      totalStudents: 28,
      attendedStudents: 25,
      delegateId: 'usr-std-009',
      delegateName: 'عصام عبد الجليل',
      isLiveNow: false,
    ),
  ];

  static final List<LabSession> labSessions = [
    LabSession(
      id: 'ses-prac-live-01',
      groupId: 'grp-001',
      groupName: 'مجموعة A - معمل البرمجيات 1',
      courseCode: 'CS301',
      courseName: 'هندسة البرمجيات المتقدمة',
      sectionNumber: '01',
      sessionDate: DateTime.now(),
      roomName: 'معمل الحاسوب 3',
      sessionState: LabSessionState.active,
      totalStudents: 30,
      attendedCount: 22,
      absentCount: 5,
      lateCount: 2,
      excusedCount: 1,
      pendingExceptionsCount: 2,
    ),
    LabSession(
      id: 'ses-prac-past-02',
      groupId: 'grp-003',
      groupName: 'مجموعة A - معمل سيسكو والشبكات',
      courseCode: 'IT302',
      courseName: 'شبكات الحاسوب المتقدمة',
      sectionNumber: '01',
      sessionDate: DateTime.now().subtract(const Duration(days: 2)),
      roomName: 'معمل الشبكات التخصصي',
      sessionState: LabSessionState.synced,
      totalStudents: 32,
      attendedCount: 29,
      absentCount: 2,
      lateCount: 1,
      excusedCount: 0,
      pendingExceptionsCount: 0,
      closedAt: DateTime.now().subtract(const Duration(days: 2, hours: 2)),
      syncedAt: DateTime.now().subtract(const Duration(days: 2, hours: 1)),
      syncRecordId: 'SYNC-REC-2026-8841',
    ),
    LabSession(
      id: 'ses-prac-past-03',
      groupId: 'grp-002',
      groupName: 'مجموعة B - معمل البرمجيات 1',
      courseCode: 'CS301',
      courseName: 'هندسة البرمجيات المتقدمة',
      sectionNumber: '02',
      sessionDate: DateTime.now().subtract(const Duration(days: 4)),
      roomName: 'معمل الحاسوب 3',
      sessionState: LabSessionState.closed,
      totalStudents: 28,
      attendedCount: 24,
      absentCount: 3,
      lateCount: 1,
      excusedCount: 0,
      pendingExceptionsCount: 1,
      closedAt: DateTime.now().subtract(const Duration(days: 4, hours: 2)),
    ),
  ];

  static List<LabStudentRecord> getLabStudentsForGroup(String groupId) {
    return [
      LabStudentRecord(
        studentId: 'std-101',
        studentNumber: 'STD-2023-4019',
        fullName: 'أحمد علي عبد الله الشميري',
        departmentName: 'هندسة تقنية المعلومات',
        groupName: 'مجموعة A',
        attendanceState: 'PRESENT',
        attendanceMethod: 'QR',
        markedAt: DateTime.now().subtract(const Duration(minutes: 35)),
        isVerified: true,
      ),
      LabStudentRecord(
        studentId: 'std-102',
        studentNumber: 'STD-2023-4022',
        fullName: 'سارة محمد القحطاني',
        departmentName: 'علوم الحاسوب',
        groupName: 'مجموعة A',
        attendanceState: 'PRESENT',
        attendanceMethod: 'BIOMETRIC',
        markedAt: DateTime.now().subtract(const Duration(minutes: 28)),
        isVerified: true,
      ),
      LabStudentRecord(
        studentId: 'std-103',
        studentNumber: 'STD-2023-4035',
        fullName: 'حسام ناصر الشمري',
        departmentName: 'هندسة تقنية المعلومات',
        groupName: 'مجموعة A',
        attendanceState: 'EXCUSED',
        attendanceMethod: 'MANUAL',
        manualReason: 'عذر طبي رسمي معتمد من الكلية',
        exceptionStatus: LabExceptionStatus.approved,
        teacherNotes: 'تم التحقق من التقرير الطبي المرفق',
        markedAt: DateTime.now().subtract(const Duration(minutes: 20)),
        isVerified: true,
      ),
      LabStudentRecord(
        studentId: 'std-104',
        studentNumber: 'STD-2023-4048',
        fullName: 'رغد خالد المطيري',
        departmentName: 'نظم المعلومات',
        groupName: 'مجموعة A',
        attendanceState: 'LATE',
        attendanceMethod: 'QR',
        markedAt: DateTime.now().subtract(const Duration(minutes: 15)),
        isVerified: true,
      ),
      const LabStudentRecord(
        studentId: 'std-105',
        studentNumber: 'STD-2023-4051',
        fullName: 'طارق زياد العمري',
        departmentName: 'علوم الحاسوب',
        groupName: 'مجموعة A',
        attendanceState: 'ABSENT',
        attendanceMethod: 'MANUAL',
        manualReason: 'عطل مفاجئ في كاميرا الهاتف ومسح الـ QR',
        exceptionStatus: LabExceptionStatus.pending,
        teacherNotes: null,
      ),
      LabStudentRecord(
        studentId: 'std-106',
        studentNumber: 'STD-2023-4066',
        fullName: 'مريم عبد الله باحارث',
        departmentName: 'هندسة تقنية المعلومات',
        groupName: 'مجموعة A',
        attendanceState: 'PRESENT',
        attendanceMethod: 'QR',
        markedAt: DateTime.now().subtract(const Duration(minutes: 42)),
        isVerified: true,
      ),
      const LabStudentRecord(
        studentId: 'std-107',
        studentNumber: 'STD-2023-4079',
        fullName: 'أيمن سالم باوزير',
        departmentName: 'علوم الحاسوب',
        groupName: 'مجموعة A',
        attendanceState: 'ABSENT',
        attendanceMethod: 'MANUAL',
        manualReason: 'طلب تحضير استثنائي للمشاركة بمسابقة البرمجة',
        exceptionStatus: LabExceptionStatus.pending,
      ),
      LabStudentRecord(
        studentId: 'std-108',
        studentNumber: 'STD-2023-4084',
        fullName: 'نوف سعد الدوسري',
        departmentName: 'هندسة تقنية المعلومات',
        groupName: 'مجموعة A',
        attendanceState: 'PRESENT',
        attendanceMethod: 'BIOMETRIC',
        markedAt: DateTime.now().subtract(const Duration(minutes: 25)),
        isVerified: true,
      ),
      LabStudentRecord(
        studentId: 'std-109',
        studentNumber: 'STD-2023-4091',
        fullName: 'فيصل عبد العزيز الحربي',
        departmentName: 'نظم المعلومات',
        groupName: 'مجموعة A',
        attendanceState: 'LATE',
        attendanceMethod: 'MANUAL',
        manualReason: 'تأخر بسبب اختبار معملي سابق',
        exceptionStatus: LabExceptionStatus.approved,
        markedAt: DateTime.now().subtract(const Duration(minutes: 10)),
        isVerified: true,
      ),
      const LabStudentRecord(
        studentId: 'std-110',
        studentNumber: 'STD-2023-4100',
        fullName: 'فاطمة محمد الأهدل',
        departmentName: 'علوم الحاسوب',
        groupName: 'مجموعة A',
        attendanceState: 'ABSENT',
        attendanceMethod: 'MANUAL',
        exceptionStatus: LabExceptionStatus.none,
      ),
    ];
  }
}
